# Generated by Django 4.2.7 on 2023-11-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('moto', models.CharField(max_length=30)),
                ('data', models.DateField()),
                ('servicos', models.CharField(max_length=255)),
                ('proprietario', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=8)),
                ('status', models.CharField(default='Aguardando aprovação', max_length=30)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motos',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('cor', models.CharField(max_length=30)),
                ('ano', models.IntegerField()),
                ('proprietario', models.IntegerField()),
                ('placa', models.CharField(max_length=8)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('kilometragem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=15)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=40)),
                ('uf', models.CharField(max_length=40)),
                ('municipio', models.CharField(max_length=40)),
            ],
        ),
    ]
