# Generated by Django 4.2.7 on 2023-11-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_br101motors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietario',
            name='cpf',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
