# Generated by Django 4.2.7 on 2023-11-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_br101motors', '0004_remove_agendamento_moto_alter_agendamento_placa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietario',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
