# Generated by Django 4.2.7 on 2023-11-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_br101motors', '0006_rename_placa_agendamento_moto_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motos',
            name='proprietario',
        ),
        migrations.AddField(
            model_name='motos',
            name='proprietario_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api_br101motors.proprietario'),
            preserve_default=False,
        ),
    ]
