# Generated by Django 4.2.7 on 2023-11-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_br101motors', '0007_remove_motos_proprietario_motos_proprietario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motos',
            name='placa',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
